---
title: |
  Sociodemographic Comparison of Caribbean Hispanic Older Adult Immigrants in the U.S. and Origin Countries
format: 
  pdf:
    keep-tex: true
    documentclass: article
    latex-engine: xelatex
header-includes:
   - \usepackage{pdflscape}
   - \usepackage{caption}
   - \usepackage{booktabs}
        
date: last-modified
tbl-cap-location: top
author:
  - name: William H. Dow
    affiliation: 1
  - name: Chris Soria
    affiliation: 1
  - name: Henry T. Dow
    affiliation: 1
affiliations:
  - name: University of California, Berkeley
    index: 1
acknowledgements: | 
  The authors wish to acknowledge the statistical offices that provided the underlying data making this research possible: National Administrative Department of Statistics, Colombia; Office of National Statistics, Cuba; National Statistics Office, Dominican Republic; Department of Statistics and Censuses, El Salvador; National Institute of Statistics, Guatemala; National Institute of Statistics, Honduras; National Institute of Statistics, Geography, and Informatics, Mexico; U.S. Bureau of the Census, Puerto Rico; and Bureau of the Census, United States.

      
abstract: |
  Caribbean and adjacent Latin American countries are key sources of Hispanic immigrants to the U.S. There has been rapid growth in the older adult Hispanic populations both among immigrants in the U.S. and in their home countries of emigration. This paper supports hypothesis generation for international comparative Hispanic aging studies by comparing older adult sociodemographic characteristics of U.S. immigrants versus those in sending countries. The analysis also provides context for the global family of health and retirement studies in the region including the ongoing Caribbean American Dementia and Aging Study (CADAS) which is collecting harmonized data on healthy aging in Puerto Rico, Dominican Republic, and Cuba. We analyze census microdata from these countries along with other major Hispanic Caribbean-adjacent sending countries including Mexico, Colombia, El Salvador, Guatemala, and Honduras. We compare older adults in these sending countries to country-specific immigrant samples in the U.S. American Community Survey, focusing on socioeconomic differences such as education, as well as marital status and co-residence patterns related to caregiver availability. We also examine differences by citizenship and immigration age to further explore immigrant selectivity patterns. The highly varied experiences of these cohorts will help inform future comparative research on Hispanic healthy aging.  
  
bibliography: us_international_ses.bib  
linestretch: 1.2
---

## Introduction and Background {#sec-intro}
Caribbean and adjacent Central and South American countries are key sources of Hispanic immigrants to the United Sates [@passel_what_2024]. In 2022, people of Mexican origin made up nearly 60% of the U.S. Hispanic population, totaling about 37.4 million. Puerto Ricans were the next largest group at 5.9 million, with an additional 3.2 million living on the island. Salvadorans, Cubans, Dominicans, Guatemalans, Colombians, and Hondurans each have populations exceeding 1 million in the United States [@noe-bustamante_key_2023]. 

These immigrant populations include a rapidly growing subgroup who are aged 65 and above, among whom there is wide variation in socioeconomic and caregiving resources. In this paper we explore sociodemographic variation of U.S. older adult immigrants by country and cohort of emigration, and compare these U.S. immigrants to the corresponding cohorts of older adults in their home countries of emigration. 

The paper is designed to support hypothesis generation for international comparative Hispanic aging studies. This includes providing background context for the global family of health and retirement studies in the region such as the ongoing Caribbean American Dementia and Aging Study (CADAS) which is collecting harmonized data on healthy aging in Puerto Rico, Dominican Republic, and Cuba[@llibre-guerra_caribbean-american_2021]. We analyze census microdata from these countries along with other major Hispanic Caribbean-adjacent sending countries including Mexico, Colombia, El Salvador, Guatemala, and Honduras. We compare older adults in these sending countries to country-specific immigrant samples in the U.S. American Community Survey, focusing on socioeconomic differences such as education, as well as marital status and co-residence patterns related to caregiver availability. We also examine differences by citizenship and immigration age to further explore immigrant selectivity patterns. The highly varied experiences of these cohorts will help inform future comparative research on Hispanic healthy aging.  


## Data and Methods

Census data for this study were obtained from IPUMS International. The current analysis draws on the latest harmonized census data available in IPUMS for Colombia (2005), Cuba (2012), the Dominican Republic (2010), El Salvador (2007), Guatemala (2002), Honduras (2001), Mexico (2020), Puerto Rico (2010), and the United States (2020). The study focused on individuals aged 65 to 89, as some datasets, such as Puerto Rico's, top-coded ages at 89. To ensure comparability, we standardized means in the international censuses based on the U.S. sex-specific age distribution. We also applied weights provided by IPUMS to make the samples nationally representative. 

Table 1 presents means of sociodemographics of all 65-89 year-olds from each country's census. The variables included are age, percent married/cohabiting, and highest educational level obtained (using internationally standardized categorizations of less than primary, primary, secondary, and university). Table 2 displays means for each country's counterparts who have immigrant to the U.S. In addition to the variables in Table 1, it includes percent English speakers, percent naturalized citizens, mean age at immigration, and mean years in the U.S. based on the American Community Survey data. Table 3 shows the same variables as in Table 2, drawn from the American Community, but categorized by race/ethnicity and nativity status.

## Preliminary Results

### Hispanic older adults in their native countries

Table 1 shows sex-specific sociodemographic characteristics among older adults aged 65 to 89, comparing across current country of residence in the Hispanic Caribbean and adjacent countries. Rates of current marriage/cohabitation are substantially higher among men than women; among women, they vary significantly across countries, ranging from 38% in the Dominican Republic to 48% in the U.S. Regarding education, there are even larger differences between neighboring countries. E.g., among women in this age group, 76% of Dominicans have less than primary education compared with 31% of Cubans and Puerto Ricans; the highest rate is Honduras at 86% and lowest is the U.S. at 4%. There are similarly large differences among men
.
### Hispanic older adults as migrants in the U.S.

Table 2 presents sociodemographics of migrants from these countries living in the U.S. The youngest groups are men from El Salvador (71.23), Guatemala (70.78), and Honduras (71.5), who are about two years younger than their counterparts in their native. The oldest group consists of Cuban women (73.35), who are slightly younger than U.S. women overall (73.75), while Cuban men (74.6) are older than the U.S. average for men (73.13). These differences reflect a combination of differential mortality rates and varying immigration patterns by birth cohort. Marital/cohabitation status is also affected by these factors as well as potentially by different cultural influences on partnership; for many countries rates are somewhat lower among immigrants in the U.S. For example, the age-adjusted married/cohabiting rate among women in Cuba is 43%, compared to 31% for Cuban-born women immigrants in the U.S.

Many of these migrant groups have low rates of reporting that they speak English, with women generally less likely to speak English than men. The lowest English speaking rates are among migrants from the Dominican Republic, where only 60% of female and 70% of male migrants speak English, and Mexico, with 65% of female and 74% of males speaking English. In contrast, migrants from Cuba (71% of females and 78% of males), Colombia (83% of females and 88% of males), and Guatemala (79% of females and 87% of males) have higher English speaking rates. 

In terms of citizenship, females are slightly more likely to become naturalized U.S. citizens than men. Typically, men emigrate to the U.S. at a younger age, about two years earlier on average. For example, females from Honduras arrive at an average age of 36.48, while males arrive at 34.42, often resulting in longer U.S. residency for men—Honduran men report an average of 37.16 years compared to women's 36.17 years. However, Guatemala is an exception; despite migrating at a younger age (32.05), Guatemalan men have spent fewer years in the U.S. (38.75) compared to women (39.26).

Men are more likely to have a college degree across all groups: Guatemalan men (12%) compared to women (8%), Honduran men (14%) versus women (11%), and Salvadoran men (10%) against women (5%). The largest gender gap is among Colombian migrants, with 24% of men holding a college degree compared to 16% of women. The least educated groups are Mexican migrants (6% of men and 4% of women with college degrees) and those from the Dominican Republic (9% for men and 7% for women). These relative gender patterns are similar to their counterparts living in their native countries (Table 1), however overall the U.S. migrants have markedly higher education than those still living in their countries of birth. 

### Race/ethnicity and nativity in U.S.

Table 3 is similar to table 2, but now looks by racial category (Black, White, and Other racial identities), Hispanic, and native-born category. Average ages across these groups are quite similar. Both Hispanic migrant and native Blacks are much less likely to be married or cohabitating, with rates of 28% and 27%, respectively. In contrast, individuals identifying as White, whether Hispanic migrant or native, are more likely to be married or cohabitating. Black migrants are slightly more likely to speak English but are less likely to become naturalized citizens. They also tend to immigrate at an older age and spend fewer years in the U.S., while Whites and those of other Hispanic races have similar immigration patterns. White Hispanic migrants have slightly longer U.S. residency. Interestingly, the college degree gap between Black and White migrants is nonexistent; both groups are equally likely to earn a degree. This contrasts with non-Hispanic US native populations, where only 17% of Black men hold a college degree compared to 36% of White men. Hispanic migrants identifying as a race other than White or Black are the least likely to have a college degree and most likely to have less than primary education, with 33% of women and 32% of men in this category having less than a primary education.

## Discussion

Ongoing analysis (to be reported in the full paper) is expanding this analysis to further examine patterns by immigration cohort, also using multivariate regression to better parse mechanisms underlying the observed differences. 

\begin{landscape}

\begin{table}[ht]
\centering
\caption{Sociodemographics by Country and Sex: Hispanics in Caribbean and Adjacent Countries}
\begingroup\small
\begin{tabular}{l|l|lllllllll}
  \hline
Gender & Demographics & Colombia & Cuba & Dominican Republic & El Salvador & Guatemala & Honduras & Mexico & Puerto Rico & United States \\ 
  \hline
Women & Age & 72.48 & 73.67 & 73.44 & 73.5 & 72.63 & 72.38 & 72.73 & 74.28 & 73.77 \\ 
   & Married/Cohabiting & 0.35 & 0.43 & 0.35 & 0.35 & 0.48 & 0.41 & 0.44 & 0.38 & 0.48 \\ 
   & Less than Primary & 0.6 & 0.31 & 0.76 & 0.84 & 0.84 & 0.86 & 0.5 & 0.31 & 0.04 \\ 
   & Primary & 0.29 & 0.5 & 0.16 & 0.11 & 0.11 & 0.09 & 0.35 & 0.26 & 0.09 \\ 
   & Secondary & 0.06 & 0.15 & 0.06 & 0.04 & 0.04 & 0.04 & 0.1 & 0.33 & 0.63 \\ 
   & University & 0.02 & 0.05 & 0.03 & 0.01 & 0.01 & - & 0.05 & 0.1 & 0.25 \\ 
   & Unknown & 0.03 & - & - & - & - & - & - & - & - \\ 
Men & Age & 72.43 & 73.58 & 73.29 & 73.93 & 73.17 & 73.01 & 72.84 & 73.51 & 73.13 \\ 
   & Married/Cohabiting & 0.67 & 0.66 & 0.67 & 0.7 & 0.79 & 0.72 & 0.73 & 0.67 & 0.7 \\ 
   & Less than Primary & 0.6 & 0.24 & 0.72 & 0.78 & 0.82 & 0.85 & 0.45 & 0.24 & 0.03 \\ 
   & Primary & 0.26 & 0.5 & 0.18 & 0.15 & 0.13 & 0.1 & 0.35 & 0.28 & 0.08 \\ 
   & Secondary & 0.06 & 0.2 & 0.06 & 0.05 & 0.03 & 0.04 & 0.09 & 0.35 & 0.55 \\ 
   & University & 0.04 & 0.06 & 0.04 & 0.02 & 0.02 & 0.01 & 0.12 & 0.13 & 0.33 \\ 
   & Unknown & 0.04 & - & - & - & - & - & - & - & - \\ 
\hline
\end{tabular}
\endgroup
\end{table}

\newpage

\begin{table}[ht]
\centering
\caption{Sociodemographics of Hispanics in the U.S. by Birth Country and Sex} 
\begingroup\small
\begin{tabular}{l|l|lllllllll}
  \hline
Gender & Demographics & Cuba & Dominican Republic & Puerto Rico & El Salvador & Guatemala & Honduras & Mexico & Colombia & United States \\ 
  \hline
Women & Age & 75.35 & 72.96 & 73.97 & 72.63 & 72.36 & 72.61 & 73.07 & 73.2 & 73.75 \\ 
   & Married/Cohabiting & 0.34 & 0.31 & 0.33 & 0.34 & 0.38 & 0.35 & 0.45 & 0.38 & 0.48 \\ 
   & English Speakers & 0.71 & 0.6 & 0.89 & 0.68 & 0.79 & 0.75 & 0.65 & 0.83 & 1 \\ 
   & Citizen & 0.84 & 0.7 & - & 0.66 & 0.69 & 0.67 & 0.57 & 0.77 & - \\ 
   & Age at Immigration & 35.63 & 37.38 & - & 36 & 33.13 & 36.48 & 31.8 & 35.38 & - \\ 
   & Years in US & 39.76 & 35.53 & - & 36.63 & 39.26 & 36.17 & 41.27 & 37.83 & - \\ 
   & Less than Primary Completed & 0.11 & 0.31 & 0.15 & 0.38 & 0.3 & 0.23 & 0.4 & 0.13 & 0.01 \\ 
   & Primary Completed & 0.21 & 0.29 & 0.25 & 0.27 & 0.23 & 0.21 & 0.3 & 0.12 & 0.08 \\ 
   & Secondary Completed & 0.5 & 0.33 & 0.48 & 0.31 & 0.38 & 0.45 & 0.27 & 0.59 & 0.66 \\ 
   & University Completed & 0.19 & 0.07 & 0.12 & 0.05 & 0.08 & 0.11 & 0.04 & 0.16 & 0.26 \\ 
  Men & Age & 74.6 & 72.24 & 73.36 & 71.23 & 70.78 & 71.5 & 72.32 & 72.98 & 73.13 \\ 
   & Married/Cohabiting & 0.63 & 0.66 & 0.61 & 0.67 & 0.65 & 0.69 & 0.73 & 0.72 & 0.7 \\ 
   & English Speakers & 0.78 & 0.7 & 0.94 & 0.78 & 0.87 & 0.83 & 0.74 & 0.88 & 1 \\ 
   & Citizen & 0.79 & 0.67 & - & 0.65 & 0.66 & 0.6 & 0.55 & 0.75 & - \\ 
   & Age at Immigration & 34.42 & 36.35 & - & 34.07 & 32.05 & 34.42 & 29.1 & 34.47 & - \\ 
   & Years in US & 40.19 & 35.89 & - & 37.2 & 38.75 & 37.16 & 43.23 & 38.55 & - \\ 
   & Less than Primary Completed & 0.11 & 0.28 & 0.15 & 0.29 & 0.25 & 0.2 & 0.39 & 0.12 & 0.01 \\ 
   & Primary Completed & 0.2 & 0.28 & 0.26 & 0.28 & 0.25 & 0.24 & 0.29 & 0.09 & 0.07 \\ 
   & Secondary Completed & 0.48 & 0.35 & 0.48 & 0.33 & 0.37 & 0.42 & 0.26 & 0.55 & 0.57 \\ 
   & University Completed & 0.22 & 0.09 & 0.11 & 0.1 & 0.12 & 0.14 & 0.06 & 0.24 & 0.34 \\ 
   \hline
\end{tabular}
\endgroup
\end{table}

\begin{table}[ht]
\centering
\caption{Sociodemographics of U.S. Older Adults by Race/Ethnicity and Nativity} 
\begingroup\small
\begin{tabular}{l|l|p{1.5cm}p{1.5cm}p{1.5cm}p{1.5cm}p{1.5cm}p{1.5cm}p{1.5cm}}
  \hline
Gender & Demographics & Hispanic Black Foreign & Hispanic White Foreign & Hispanic Other Foreign & Non-Hispanic Black Native & Non-Hispanic White Native & Non-Hispanic Other Native & All Native Hispanic \\ 
  \hline
Women & Age & 73.74 & 73.75 & 73.14 & 73.19 & 73.87 & 72.96 & 73.17 \\ 
   & Married/Cohabiting & 0.28 & 0.4 & 0.38 & 0.27 & 0.51 & 0.42 & 0.41 \\ 
   & English Speakers & 0.75 & 0.72 & 0.7 & - & - & 0.99 & 0.99 \\ 
   & Citizen & 0.51 & 0.55 & 0.53 & - & - & - & - \\ 
   & Age at Immigration & 37.29 & 33.49 & 33.79 & - & - & - & - \\ 
   & Years in US & 36.58 & 40.17 & 39.23 & - & - & - & - \\ 
   & Less than Primary Completed & 0.24 & 0.26 & 0.33 & 0.03 & 0.01 & 0.03 & 0.08 \\ 
   & Primary Completed & 0.25 & 0.26 & 0.27 & 0.15 & 0.06 & 0.09 & 0.17 \\ 
   & Secondary Completed & 0.41 & 0.38 & 0.34 & 0.64 & 0.66 & 0.6 & 0.62 \\ 
   & University Completed & 0.1 & 0.1 & 0.07 & 0.18 & 0.27 & 0.27 & 0.13 \\ 
  Men & Age & 72.85 & 73.01 & 72.36 & 72.37 & 73.25 & 72.59 & 72.5 \\ 
   & Married/Cohabiting & 0.55 & 0.69 & 0.68 & 0.52 & 0.72 & 0.63 & 0.61 \\ 
   & English Speakers & 0.8 & 0.79 & 0.78 & - & - & - & 0.99 \\ 
   & Citizen & 0.49 & 0.53 & 0.51 & - & - & - & - \\ 
   & Age at Immigration & 34.78 & 31.13 & 31.42 & - & - & - & - \\ 
   & Years in US & 37.95 & 41.8 & 40.79 & - & - & - & - \\ 
   & Less than Primary Completed & 0.22 & 0.26 & 0.32 & 0.04 & 0.01 & 0.03 & 0.07 \\ 
   & Primary Completed & 0.26 & 0.25 & 0.27 & 0.16 & 0.06 & 0.08 & 0.15 \\ 
   & Secondary Completed & 0.4 & 0.37 & 0.33 & 0.63 & 0.57 & 0.57 & 0.6 \\ 
   & University Completed & 0.11 & 0.12 & 0.08 & 0.17 & 0.36 & 0.32 & 0.18 \\ 
   \hline
\end{tabular}
\endgroup
\end{table}

\end{landscape}
# References

